//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs_Fatal
    {
        public long LogFatalId { get; set; }
        public System.DateTime LoggedDate { get; set; }
        public string ApplicationId { get; set; }
        public string Namespace { get; set; }
        public string Classname { get; set; }
        public string Functionname { get; set; }
        public string Area { get; set; }
        public string Message { get; set; }
    }
}
