//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MRF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_MRF()
        {
            this.TAB_MRF_DETAILS = new HashSet<TAB_MRF_DETAILS>();
        }
    
        public System.Guid MRP_INETRNAL_ID { get; set; }
        public string MRF_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public Nullable<short> REC_TYPE { get; set; }
        public Nullable<System.Guid> WORKFLOW_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MRF_STATUS { get; set; }
        public Nullable<System.DateTime> FINAL_ACTION_DATE { get; set; }
        public int MRF_CODE { get; set; }
        public string ReplaceType { get; set; }
    
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
        public virtual TAB_WORKFLOW_MASTER TAB_WORKFLOW_MASTER { get; set; }
        public virtual TAB_WORKFLOW_MASTER TAB_WORKFLOW_MASTER1 { get; set; }
        public virtual TAB_WORKFLOW_MASTER TAB_WORKFLOW_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MRF_DETAILS> TAB_MRF_DETAILS { get; set; }
    }
}
