//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ALL_MAIL
    {
        public int MAIL_SEQ { get; set; }
        public string TO_MAIL { get; set; }
        public string CC_MAIL { get; set; }
        public string MAIL_CONTENT { get; set; }
        public Nullable<System.DateTime> MAIL_INSERT_DATE { get; set; }
        public Nullable<System.DateTime> MAIL_SENT_DATE { get; set; }
        public Nullable<short> MAIL_FLAG { get; set; }
        public string MAIL_REMARK { get; set; }
        public string USER_ID { get; set; }
    }
}
