//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_SPECIAL_ALLOWANCE
    {
        public System.Guid SPECIAL_ALLOWANCE_ID { get; set; }
        public System.Guid WF_ID { get; set; }
        public short YEAR_ID { get; set; }
        public short MONTH_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public System.Guid CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
        public string Remark { get; set; }
    }
}
