//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MRF_DETAILS
    {
        public System.Guid TAB_MRF_DETAIL_ID { get; set; }
        public System.Guid MRP_INETRNAL_ID { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
        public Nullable<System.Guid> FLOOR_ID { get; set; }
        public Nullable<System.Guid> SKILL_ID { get; set; }
        public Nullable<short> WF_DESIGNATION_ID { get; set; }
        public Nullable<short> WF_EMP_TYPE { get; set; }
        public Nullable<short> WOKFORCE_QUANTITY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public int HIRING_QUANTITY { get; set; }
        public System.Guid SUBDEPT_ID { get; set; }
    
        public virtual TAB_BUILDING_MASTER TAB_BUILDING_MASTER { get; set; }
        public virtual TAB_DEPARTMENT_MASTER TAB_DEPARTMENT_MASTER { get; set; }
        public virtual TAB_MRF TAB_MRF { get; set; }
        public virtual TAB_SKILL_MASTER TAB_SKILL_MASTER { get; set; }
        public virtual TAB_WF_DESIGNATION_MASTER TAB_WF_DESIGNATION_MASTER { get; set; }
        public virtual TAB_WORFORCE_TYPE TAB_WORFORCE_TYPE { get; set; }
        public virtual TAB_SUBDEPARTMENT_MASTER TAB_SUBDEPARTMENT_MASTER { get; set; }
    }
}
