//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_COMPANY_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_COMPANY_MASTER()
        {
            this.TAB_AGENCY_MASTER = new HashSet<TAB_AGENCY_MASTER>();
            this.TAB_AGENCY_MASTER1 = new HashSet<TAB_AGENCY_MASTER>();
            this.TAB_AGENCY_MASTER2 = new HashSet<TAB_AGENCY_MASTER>();
            this.TAB_BIOMETRIC = new HashSet<TAB_BIOMETRIC>();
            this.TAB_BIOMETRIC1 = new HashSet<TAB_BIOMETRIC>();
            this.TAB_BIOMETRIC2 = new HashSet<TAB_BIOMETRIC>();
            this.TAB_BUILDING_MASTER = new HashSet<TAB_BUILDING_MASTER>();
            this.TAB_BUILDING_MASTER1 = new HashSet<TAB_BUILDING_MASTER>();
            this.TAB_BUILDING_MASTER2 = new HashSet<TAB_BUILDING_MASTER>();
            this.TAB_DEPARTMENT_MASTER = new HashSet<TAB_DEPARTMENT_MASTER>();
            this.TAB_DEPARTMENT_MASTER1 = new HashSet<TAB_DEPARTMENT_MASTER>();
            this.TAB_DEPARTMENT_MASTER2 = new HashSet<TAB_DEPARTMENT_MASTER>();
            this.TAB_EMP_STATUS_MASTER = new HashSet<TAB_EMP_STATUS_MASTER>();
            this.TAB_EMP_STATUS_MASTER1 = new HashSet<TAB_EMP_STATUS_MASTER>();
            this.TAB_EMP_STATUS_MASTER2 = new HashSet<TAB_EMP_STATUS_MASTER>();
            this.TAB_EMPL_TYPE_MASTER = new HashSet<TAB_EMPL_TYPE_MASTER>();
            this.TAB_EMPL_TYPE_MASTER1 = new HashSet<TAB_EMPL_TYPE_MASTER>();
            this.TAB_EMPL_TYPE_MASTER2 = new HashSet<TAB_EMPL_TYPE_MASTER>();
            this.TAB_FLOOR_MASTER = new HashSet<TAB_FLOOR_MASTER>();
            this.TAB_FLOOR_MASTER1 = new HashSet<TAB_FLOOR_MASTER>();
            this.TAB_FLOOR_MASTER2 = new HashSet<TAB_FLOOR_MASTER>();
            this.TAB_LOGIN_MASTER = new HashSet<TAB_LOGIN_MASTER>();
            this.TAB_LOGIN_MASTER1 = new HashSet<TAB_LOGIN_MASTER>();
            this.TAB_LOGIN_MASTER2 = new HashSet<TAB_LOGIN_MASTER>();
            this.TAB_MARITAL_STATUS_MASTER = new HashSet<TAB_MARITAL_STATUS_MASTER>();
            this.TAB_MARITAL_STATUS_MASTER1 = new HashSet<TAB_MARITAL_STATUS_MASTER>();
            this.TAB_MARITAL_STATUS_MASTER2 = new HashSet<TAB_MARITAL_STATUS_MASTER>();
            this.TAB_MENU_MASTER = new HashSet<TAB_MENU_MASTER>();
            this.TAB_MENU_MASTER1 = new HashSet<TAB_MENU_MASTER>();
            this.TAB_MENU_MASTER2 = new HashSet<TAB_MENU_MASTER>();
            this.TAB_MRF = new HashSet<TAB_MRF>();
            this.TAB_MRF1 = new HashSet<TAB_MRF>();
            this.TAB_MRF2 = new HashSet<TAB_MRF>();
            this.TAB_REC_MASTER = new HashSet<TAB_REC_MASTER>();
            this.TAB_REC_MASTER1 = new HashSet<TAB_REC_MASTER>();
            this.TAB_REC_MASTER2 = new HashSet<TAB_REC_MASTER>();
            this.TAB_ROLE_MASTER = new HashSet<TAB_ROLE_MASTER>();
            this.TAB_ROLE_MASTER1 = new HashSet<TAB_ROLE_MASTER>();
            this.TAB_ROLE_MASTER2 = new HashSet<TAB_ROLE_MASTER>();
            this.TAB_SHIFT_MASTER = new HashSet<TAB_SHIFT_MASTER>();
            this.TAB_SHIFT_MASTER1 = new HashSet<TAB_SHIFT_MASTER>();
            this.TAB_SHIFT_MASTER2 = new HashSet<TAB_SHIFT_MASTER>();
            this.TAB_SKILL_MASTER = new HashSet<TAB_SKILL_MASTER>();
            this.TAB_SKILL_MASTER1 = new HashSet<TAB_SKILL_MASTER>();
            this.TAB_SKILL_MASTER2 = new HashSet<TAB_SKILL_MASTER>();
            this.TAB_WF_DESIGNATION_MASTER = new HashSet<TAB_WF_DESIGNATION_MASTER>();
            this.TAB_WF_DESIGNATION_MASTER1 = new HashSet<TAB_WF_DESIGNATION_MASTER>();
            this.TAB_WF_DESIGNATION_MASTER2 = new HashSet<TAB_WF_DESIGNATION_MASTER>();
            this.TAB_WF_WORK_DETAILS = new HashSet<TAB_WF_WORK_DETAILS>();
            this.TAB_WF_WORK_DETAILS1 = new HashSet<TAB_WF_WORK_DETAILS>();
            this.TAB_WF_WORK_DETAILS2 = new HashSet<TAB_WF_WORK_DETAILS>();
            this.TAB_WORFORCE_TYPE = new HashSet<TAB_WORFORCE_TYPE>();
            this.TAB_WORFORCE_TYPE1 = new HashSet<TAB_WORFORCE_TYPE>();
            this.TAB_WORFORCE_TYPE2 = new HashSet<TAB_WORFORCE_TYPE>();
            this.TAB_WORKFLOW_MASTER = new HashSet<TAB_WORKFLOW_MASTER>();
            this.TAB_WORKFORCE_EDU_MASTER = new HashSet<TAB_WORKFORCE_EDU_MASTER>();
            this.TAB_WORKFORCE_MASTER = new HashSet<TAB_WORKFORCE_MASTER>();
            this.TAB_WORKFLOW_MASTER1 = new HashSet<TAB_WORKFLOW_MASTER>();
            this.TAB_WORKFORCE_EDU_MASTER1 = new HashSet<TAB_WORKFORCE_EDU_MASTER>();
            this.TAB_WORKFORCE_MASTER1 = new HashSet<TAB_WORKFORCE_MASTER>();
            this.TAB_WORKFLOW_MASTER2 = new HashSet<TAB_WORKFLOW_MASTER>();
            this.TAB_WORKFORCE_EDU_MASTER2 = new HashSet<TAB_WORKFORCE_EDU_MASTER>();
            this.TAB_WORKFORCE_MASTER2 = new HashSet<TAB_WORKFORCE_MASTER>();
            this.TAB_SUBDEPARTMENT_MASTER = new HashSet<TAB_SUBDEPARTMENT_MASTER>();
            this.TAB_ITEM_CODE = new HashSet<TAB_ITEM_CODE>();
        }
    
        public System.Guid COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public System.DateTime Created_date { get; set; }
        public string Created_by { get; set; }
        public string Status { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_AGENCY_MASTER> TAB_AGENCY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_AGENCY_MASTER> TAB_AGENCY_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_AGENCY_MASTER> TAB_AGENCY_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BIOMETRIC> TAB_BIOMETRIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BIOMETRIC> TAB_BIOMETRIC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BIOMETRIC> TAB_BIOMETRIC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BUILDING_MASTER> TAB_BUILDING_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BUILDING_MASTER> TAB_BUILDING_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BUILDING_MASTER> TAB_BUILDING_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_DEPARTMENT_MASTER> TAB_DEPARTMENT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_DEPARTMENT_MASTER> TAB_DEPARTMENT_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_DEPARTMENT_MASTER> TAB_DEPARTMENT_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_EMP_STATUS_MASTER> TAB_EMP_STATUS_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_EMP_STATUS_MASTER> TAB_EMP_STATUS_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_EMP_STATUS_MASTER> TAB_EMP_STATUS_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_EMPL_TYPE_MASTER> TAB_EMPL_TYPE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_EMPL_TYPE_MASTER> TAB_EMPL_TYPE_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_EMPL_TYPE_MASTER> TAB_EMPL_TYPE_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_FLOOR_MASTER> TAB_FLOOR_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_FLOOR_MASTER> TAB_FLOOR_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_FLOOR_MASTER> TAB_FLOOR_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_LOGIN_MASTER> TAB_LOGIN_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_LOGIN_MASTER> TAB_LOGIN_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_LOGIN_MASTER> TAB_LOGIN_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MARITAL_STATUS_MASTER> TAB_MARITAL_STATUS_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MARITAL_STATUS_MASTER> TAB_MARITAL_STATUS_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MARITAL_STATUS_MASTER> TAB_MARITAL_STATUS_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MENU_MASTER> TAB_MENU_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MENU_MASTER> TAB_MENU_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MENU_MASTER> TAB_MENU_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MRF> TAB_MRF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MRF> TAB_MRF1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MRF> TAB_MRF2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_REC_MASTER> TAB_REC_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_REC_MASTER> TAB_REC_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_REC_MASTER> TAB_REC_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ROLE_MASTER> TAB_ROLE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ROLE_MASTER> TAB_ROLE_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ROLE_MASTER> TAB_ROLE_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SHIFT_MASTER> TAB_SHIFT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SHIFT_MASTER> TAB_SHIFT_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SHIFT_MASTER> TAB_SHIFT_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SKILL_MASTER> TAB_SKILL_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SKILL_MASTER> TAB_SKILL_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SKILL_MASTER> TAB_SKILL_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_DESIGNATION_MASTER> TAB_WF_DESIGNATION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_DESIGNATION_MASTER> TAB_WF_DESIGNATION_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_DESIGNATION_MASTER> TAB_WF_DESIGNATION_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_WORK_DETAILS> TAB_WF_WORK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_WORK_DETAILS> TAB_WF_WORK_DETAILS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_WORK_DETAILS> TAB_WF_WORK_DETAILS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORFORCE_TYPE> TAB_WORFORCE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORFORCE_TYPE> TAB_WORFORCE_TYPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORFORCE_TYPE> TAB_WORFORCE_TYPE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFLOW_MASTER> TAB_WORKFLOW_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_EDU_MASTER> TAB_WORKFORCE_EDU_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_MASTER> TAB_WORKFORCE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFLOW_MASTER> TAB_WORKFLOW_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_EDU_MASTER> TAB_WORKFORCE_EDU_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_MASTER> TAB_WORKFORCE_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFLOW_MASTER> TAB_WORKFLOW_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_EDU_MASTER> TAB_WORKFORCE_EDU_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_MASTER> TAB_WORKFORCE_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SUBDEPARTMENT_MASTER> TAB_SUBDEPARTMENT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ITEM_CODE> TAB_ITEM_CODE { get; set; }
    }
}
