//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAB_GATEPASS
    {
        public System.Guid ID { get; set; }
        public System.Guid WORKFORCE_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public System.TimeSpan OUT_TIME { get; set; }
        public System.TimeSpan IN_TIME { get; set; }
        public Nullable<System.TimeSpan> ACTUAL_OUTTIME { get; set; }
        public Nullable<System.TimeSpan> ACTUAL_INTIME { get; set; }
        public string PURPOSE { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public System.Guid DEPT_ID { get; set; }
        public short WF_EMP_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.Guid SUBDEPT_ID { get; set; }
        [MaxLength]
        public string WORKFORCE_IDS { get; set; }
        public string MOBILE_NO { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
    
        public virtual TAB_DEPARTMENT_MASTER TAB_DEPARTMENT_MASTER { get; set; }
        public virtual TAB_WORFORCE_TYPE TAB_WORFORCE_TYPE { get; set; }
        public virtual TAB_SUBDEPARTMENT_MASTER TAB_SUBDEPARTMENT_MASTER { get; set; }
        public virtual TAB_WORKFORCE_MASTER TAB_WORKFORCE_MASTER { get; set; }
    }
}
