//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ITEM_OPERATION_MASTER
    {
        public System.Guid UNIQUE_OPERATION_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public Nullable<System.Guid> DEPT_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<System.Guid> ITEM_ID { get; set; }
        public Nullable<double> RATE { get; set; }
        public string OPERATION { get; set; }
        public string PERCENTAGE { get; set; }
        public Nullable<System.DateTime> RATE_APPLIED_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
    }
}
