//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WF_WORK_DETAILS
    {
        public System.Guid WF_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public Nullable<System.DateTime> WORK_DATE { get; set; }
        public Nullable<System.Guid> DEPT_ID { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
        public Nullable<System.Guid> FLOOR_ID { get; set; }
        public Nullable<System.Guid> SHIFT_ID { get; set; }
        public Nullable<System.Guid> ITEM_ID { get; set; }
        public Nullable<System.Guid> UNIQUE_OPERATION_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
    
        public virtual TAB_BUILDING_MASTER TAB_BUILDING_MASTER { get; set; }
        public virtual TAB_DEPARTMENT_MASTER TAB_DEPARTMENT_MASTER { get; set; }
        public virtual TAB_FLOOR_MASTER TAB_FLOOR_MASTER { get; set; }
        public virtual TAB_SHIFT_MASTER TAB_SHIFT_MASTER { get; set; }
        public virtual TAB_WORKFORCE_MASTER TAB_WORKFORCE_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
    }
}
