//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_BIOMETRIC
    {
        public int ID { get; set; }
        public System.Guid WORKFORCE_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public string BIOMETRIC_CODE { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string DEVICEID { get; set; }
        public Nullable<System.DateTime> ATTENDANCE_DATE { get; set; }
        public string STATUS_CODE { get; set; }
        public Nullable<int> SHIFT_ID { get; set; }
        public Nullable<System.TimeSpan> SHIFT_BREAK1STARTTIME { get; set; }
        public Nullable<System.TimeSpan> SHIFT_BREAK1ENDTIME { get; set; }
        public Nullable<System.DateTime> INSERTED_ON { get; set; }
        public Nullable<long> ATTENDANCELOG_ID { get; set; }
        public Nullable<int> MDBFILEID { get; set; }
        public Nullable<int> IN_SEQID { get; set; }
        public string Present { get; set; }
        public string Absent { get; set; }
        public string Status { get; set; }
        public string OverTime { get; set; }
        public string EarlyBy { get; set; }
        public string LateBy { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public string Duration { get; set; }
        public string PunchRecords { get; set; }
    
        public virtual TAB_WORKFORCE_MASTER TAB_WORKFORCE_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
    }
}
