//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ROLE_MENU_MAPPING
    {
        public Nullable<System.Guid> ROLE_ID { get; set; }
        public Nullable<System.Guid> MENU_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
    
        public virtual TAB_MENU_MASTER TAB_MENU_MASTER { get; set; }
        public virtual TAB_ROLE_MASTER TAB_ROLE_MASTER { get; set; }
        public virtual TAB_ROLE_MASTER TAB_ROLE_MASTER1 { get; set; }
        public virtual TAB_ROLE_MASTER TAB_ROLE_MASTER2 { get; set; }
    }
}
