//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_TRAINNING_WORKFORCE
    {
        public System.Guid TRAINNING_WORKFORCE_ID { get; set; }
        public System.Guid CMP_ID { get; set; }
        public Nullable<System.Guid> WF_ID { get; set; }
        public string ISCOMPLETED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
        public string WORKFORCES { get; set; }
        public Nullable<System.Guid> DEPT_ID { get; set; }
        public Nullable<System.Guid> SUB_DEPT_ID { get; set; }
        public Nullable<short> EMP_TYPES { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
        public byte[] TRAINNING_PHOTO { get; set; }
    }
}
