//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ALL_WHATSAPP
    {
        public int WHATSAPP_SEQ { get; set; }
        public string MOBILE_NO { get; set; }
        public string SMS_TEXT { get; set; }
        public Nullable<System.DateTime> SMS_INSERT_DATE { get; set; }
        public Nullable<System.DateTime> SMS_SENT_DATE { get; set; }
        public Nullable<short> SMS_FLAG { get; set; }
        public string SMS_REMARK { get; set; }
        public string USER_ID { get; set; }
    }
}
