//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ASSET_MASTER
    {
        public System.Guid ASSET_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public System.Guid DEPARTMENT_ID { get; set; }
        public System.Guid SUBDEPT_ID { get; set; }
        public string ASSET_NAME { get; set; }
        public Nullable<int> ASSET_LIFE { get; set; }
        public string REFUNDABLE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
    }
}
