//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_EMPLOYEE_TRANSFER
    {
        public int ID { get; set; }
        public Nullable<System.Guid> WF_ID { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
        public Nullable<System.Guid> DEPT_ID { get; set; }
        public Nullable<System.Guid> SUB_DEPT_ID { get; set; }
        public Nullable<int> EMPLOYMENT_TYPE { get; set; }
        public Nullable<System.DateTime> REQUESTED_DATE { get; set; }
        public string REQUESTED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<int> IS_APPROVED { get; set; }
        public string Remark { get; set; }
    }
}
