//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFORCE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_WORKFORCE_MASTER()
        {
            this.TAB_WF_WORK_DETAILS = new HashSet<TAB_WF_WORK_DETAILS>();
            this.TAB_WORKFORCE_LEAVES = new HashSet<TAB_WORKFORCE_LEAVES>();
            this.TAB_BIOMETRIC = new HashSet<TAB_BIOMETRIC>();
            this.TAB_WORKFORCE_SALARY = new HashSet<TAB_WORKFORCE_SALARY>();
            this.TAB_WORKFORCE_PHOTO_MASTER = new HashSet<TAB_WORKFORCE_PHOTO_MASTER>();
            this.TAB_GATEPASS = new HashSet<TAB_GATEPASS>();
            this.TAB_TOOL_TALK_DAILY_CHECKLIST = new HashSet<TAB_TOOL_TALK_DAILY_CHECKLIST>();
        }
    
        public System.Guid WF_ID { get; set; }
        public string EMP_ID { get; set; }
        public short WF_EMP_TYPE { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public Nullable<System.Guid> AGENCY_ID { get; set; }
        public string BIOMETRIC_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.Guid> DEPT_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<short> WF_EDUCATION_ID { get; set; }
        public Nullable<short> MARITAL_ID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOJ_AS_PER_EPF { get; set; }
        public Nullable<short> WF_DESIGNATION_ID { get; set; }
        public Nullable<System.Guid> SKILL_ID { get; set; }
        public Nullable<short> EMP_TYPE_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string ALTERNATE_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public string PRESENT_ADDRESS { get; set; }
        public Nullable<System.Guid> PRESENT_ADDRESS_CITY { get; set; }
        public Nullable<System.Guid> PRESENT_ADDRESS_STATE { get; set; }
        public Nullable<int> PRESENT_ADDRESS_PIN { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public Nullable<System.Guid> PERMANENT_ADDRESS_CITY { get; set; }
        public Nullable<System.Guid> PERMANENT_ADDRESS_STATE { get; set; }
        public Nullable<int> PERMANENT_ADDRESS_PIN { get; set; }
        public Nullable<long> AADHAR_NO { get; set; }
        public Nullable<short> EMP_STATUS_ID { get; set; }
        public string IDENTIFICATION_MARK { get; set; }
        public Nullable<System.DateTime> EXIT_DATE { get; set; }
        public string EXIT_REASON { get; set; }
        public Nullable<System.DateTime> RETIREMMENT_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.Guid> MRF_INTERNAL_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string REFERENCE_ID { get; set; }
        public Nullable<System.Guid> SUBDEPT_ID { get; set; }
        public Nullable<short> TimePeriod { get; set; }
        public System.Guid BUILDING_ID { get; set; }
    
        public virtual TAB_AGENCY_MASTER TAB_AGENCY_MASTER { get; set; }
        public virtual TAB_DEPARTMENT_MASTER TAB_DEPARTMENT_MASTER { get; set; }
        public virtual TAB_EMP_STATUS_MASTER TAB_EMP_STATUS_MASTER { get; set; }
        public virtual TAB_EMPL_TYPE_MASTER TAB_EMPL_TYPE_MASTER { get; set; }
        public virtual TAB_MARITAL_STATUS_MASTER TAB_MARITAL_STATUS_MASTER { get; set; }
        public virtual TAB_SKILL_MASTER TAB_SKILL_MASTER { get; set; }
        public virtual TAB_STATE_CITY_MASTER TAB_STATE_CITY_MASTER { get; set; }
        public virtual TAB_STATE_CITY_MASTER TAB_STATE_CITY_MASTER1 { get; set; }
        public virtual TAB_STATE_MASTER TAB_STATE_MASTER { get; set; }
        public virtual TAB_STATE_MASTER TAB_STATE_MASTER1 { get; set; }
        public virtual TAB_WF_DESIGNATION_MASTER TAB_WF_DESIGNATION_MASTER { get; set; }
        public virtual TAB_WORFORCE_TYPE TAB_WORFORCE_TYPE { get; set; }
        public virtual TAB_WORKFORCE_EDU_MASTER TAB_WORKFORCE_EDU_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_WORK_DETAILS> TAB_WF_WORK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_LEAVES> TAB_WORKFORCE_LEAVES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BIOMETRIC> TAB_BIOMETRIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_SALARY> TAB_WORKFORCE_SALARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WORKFORCE_PHOTO_MASTER> TAB_WORKFORCE_PHOTO_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
        public virtual TAB_SUBDEPARTMENT_MASTER TAB_SUBDEPARTMENT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_GATEPASS> TAB_GATEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_TOOL_TALK_DAILY_CHECKLIST> TAB_TOOL_TALK_DAILY_CHECKLIST { get; set; }
    }
}
