//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFORCE_EXIT
    {
        public System.Guid EXIT_ID { get; set; }
        public System.Guid DEPT_ID { get; set; }
        public System.Guid WF_ID { get; set; }
        public string IS_NOTICE_SERVE { get; set; }
        public byte NOTICE_DAYS { get; set; }
        public string REASON_OF_LEAVING { get; set; }
        public System.DateTime RESIGNATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.Guid> COMPANY_ID { get; set; }
    }
}
