//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WF_WORK_DETAILS_OLD
    {
        public System.Guid WF_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public Nullable<System.DateTime> WORK_DATE { get; set; }
        public Nullable<System.Guid> DEPT_ID { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
        public Nullable<System.Guid> FLOOR_ID { get; set; }
        public Nullable<System.Guid> SHIFT_ID { get; set; }
        public Nullable<System.Guid> ITEM_ID { get; set; }
        public Nullable<System.Guid> UNIQUE_OPERATION_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
    }
}
