//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFORCE_DAILYWORK
    {
        public System.Guid ID { get; set; }
        public System.Guid WF_ID { get; set; }
        public double RATE { get; set; }
        public Nullable<System.DateTime> WORK_DATE { get; set; }
        public System.Guid UNIQUE_OPERATION_ID { get; set; }
        public System.Guid ITEM_ID { get; set; }
        public decimal QTY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string Operation { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string MachineNo { get; set; }
        public Nullable<decimal> AvgPercentage { get; set; }
        public Nullable<decimal> WASTE { get; set; }
        public Nullable<decimal> REJECTION_ON_LOOM { get; set; }
        public Nullable<decimal> REJECTION_ON_FINISHING { get; set; }
    }
}
