//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_FAULTY_PUNCHES
    {
        public int ID { get; set; }
        public string BIOMETRIC_CODE { get; set; }
        public Nullable<System.DateTime> ATTENDANCE_DATE { get; set; }
        public string PUNCH_RECORD { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> INSERTED_ON { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> mdbid { get; set; }
    }
}
