//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MENU_ROLE_MAPPING
    {
        public System.Guid ID { get; set; }
        public System.Guid MENU_ID { get; set; }
        public System.Guid SUBMENU_ID { get; set; }
        public System.Guid ROLE_ID { get; set; }
    
        public virtual TAB_MENU TAB_MENU { get; set; }
        public virtual TAB_ROLE_MASTER TAB_ROLE_MASTER { get; set; }
        public virtual TAB_SUBMENU TAB_SUBMENU { get; set; }
    }
}
