//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFORCE
    {
        public System.Guid ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string STATE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_NO { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
