//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFLOW_MAPPING_MASTER
    {
        public System.Guid WORKFLOWMAPPING_ID { get; set; }
        public System.Guid WORKFLOW_ID { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<System.Guid> ROLE_ID { get; set; }
        public System.Guid USER_ID { get; set; }
        public Nullable<System.Guid> DESGINATED_AUTHORITY_EMP_ID { get; set; }
        public string AUTO_APPROVE { get; set; }
        public Nullable<int> AUTO_APPROVE_DAY { get; set; }
        public string AUTO_REJECT { get; set; }
        public Nullable<int> AUTO_REJECT_DAY { get; set; }
        public System.DateTime created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string status { get; set; }
    }
}
