//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ASSET_ALLOCATION
    {
        public System.Guid ASSET_ALLOCATION_ID { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public System.Guid DEPT_ID { get; set; }
        public System.Guid SUBDEPT_ID { get; set; }
        public System.Guid WF_ID { get; set; }
        public System.Guid ASSET_ID { get; set; }
        public string ASSET_TYPE { get; set; }
        public int QUANTITY { get; set; }
        public string PURPOSE { get; set; }
        public string IS_REFOUND { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime ASSET_ASSIGN_DATE { get; set; }
        public string ASSET_ASSIGN_BY { get; set; }
        public Nullable<System.DateTime> ASSET_HANDOVER_DATE { get; set; }
        public Nullable<System.DateTime> ASSET_CLOSE_DATE { get; set; }
        public string ASSET_CLOSE_BY { get; set; }
        public byte[] TRAINNING_PHOTO { get; set; }
    }
}
