//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_BUILDING_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_BUILDING_MASTER()
        {
            this.TAB_FLOOR_MASTER = new HashSet<TAB_FLOOR_MASTER>();
            this.TAB_WF_WORK_DETAILS = new HashSet<TAB_WF_WORK_DETAILS>();
            this.TAB_BUILDING_DEPARTMENT_MAPPING = new HashSet<TAB_BUILDING_DEPARTMENT_MAPPING>();
            this.TAB_MRF_DETAILS = new HashSet<TAB_MRF_DETAILS>();
        }
    
        public System.Guid BUILDING_ID { get; set; }
        public string BUILDING_NAME { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public string BUILDING_ADDRESS { get; set; }
        public System.DateTime created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_FLOOR_MASTER> TAB_FLOOR_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_WF_WORK_DETAILS> TAB_WF_WORK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_BUILDING_DEPARTMENT_MAPPING> TAB_BUILDING_DEPARTMENT_MAPPING { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MRF_DETAILS> TAB_MRF_DETAILS { get; set; }
    }
}
