//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_TRAINNING_WORKFORCE_MAPPING
    {
        public System.Guid TRAINNING_MAPPING_ID { get; set; }
        public System.Guid TRAINNING_WORKFORCE_ID { get; set; }
        public System.Guid TRAINNING_ID { get; set; }
        public System.DateTime TRAINNING_START_DATE { get; set; }
        public System.DateTime TRAINNING_END_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_START_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_END_DATE { get; set; }
        public string ISCOMPLETED { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string STATUS { get; set; }
        public string REMARK { get; set; }
        public string VENUE { get; set; }
        public string TRANING_TIMES { get; set; }
        public string TRAINNER_NAME { get; set; }
        public string PRESENTED_EMP { get; set; }
    }
}
