//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_LOGIN_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_LOGIN_MASTER()
        {
            this.TAB_USER_ROLE_MAPPING = new HashSet<TAB_USER_ROLE_MAPPING>();
            this.TAB_USER_ROLE_MAPPING1 = new HashSet<TAB_USER_ROLE_MAPPING>();
            this.TAB_USER_ROLE_MAPPING2 = new HashSet<TAB_USER_ROLE_MAPPING>();
            this.TAB_USER_DEPARTMENT_MAPPING = new HashSet<TAB_USER_DEPARTMENT_MAPPING>();
        }
    
        public System.Guid USER_ID { get; set; }
        public string USER_LOGIN_ID { get; set; }
        public string USER_NAME { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public string MAIL_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string CURRENT_PASSWORD { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public string LAST_LOGIN_IP { get; set; }
        public int WRONG_ATTEMP_COUNT { get; set; }
        public Nullable<System.DateTime> PASSWORD_CHANGE_DATE { get; set; }
        public Nullable<int> PASSWORD_EXPIRY_DAY { get; set; }
        public string PASSWORD1 { get; set; }
        public string PASSWORD2 { get; set; }
        public string PASSWORD3 { get; set; }
        public System.DateTime created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string status { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
    
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_DEPARTMENT_MAPPING> TAB_USER_DEPARTMENT_MAPPING { get; set; }
    }
}
