//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFORCE_PHOTO_MASTER
    {
        public System.Guid PHOTO_ID { get; set; }
        public System.Guid WF_ID { get; set; }
        public byte[] PHOTO { get; set; }
        public byte[] EMP_SIGNATURE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual TAB_WORKFORCE_MASTER TAB_WORKFORCE_MASTER { get; set; }
    }
}
