//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_REC_MASTER
    {
        public short REC_TYPE { get; set; }
        public string REC_NAME { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public Nullable<System.Guid> WORKFLOW_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string STATUS { get; set; }
    
        public virtual TAB_WORKFLOW_MASTER TAB_WORKFLOW_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
    }
}
