//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_TOOL_TALK_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_TOOL_TALK_MASTER()
        {
            this.TAB_TOOL_TALK_CONFIGURATION = new HashSet<TAB_TOOL_TALK_CONFIGURATION>();
            this.TAB_TOOL_TALK_CONFIGURATION1 = new HashSet<TAB_TOOL_TALK_CONFIGURATION>();
            this.TAB_TOOL_TALK_DAILY_CHECKLIST = new HashSet<TAB_TOOL_TALK_DAILY_CHECKLIST>();
            this.TAB_TOOL_TALK_CONFIG_DAILY_ITEMS = new HashSet<TAB_TOOL_TALK_CONFIG_DAILY_ITEMS>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid DEPT_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.Guid SUBDEPT_ID { get; set; }
        public Nullable<System.Guid> BUILDING_ID { get; set; }
    
        public virtual TAB_DEPARTMENT_MASTER TAB_DEPARTMENT_MASTER { get; set; }
        public virtual TAB_DEPARTMENT_MASTER TAB_DEPARTMENT_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_TOOL_TALK_CONFIGURATION> TAB_TOOL_TALK_CONFIGURATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_TOOL_TALK_CONFIGURATION> TAB_TOOL_TALK_CONFIGURATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_TOOL_TALK_DAILY_CHECKLIST> TAB_TOOL_TALK_DAILY_CHECKLIST { get; set; }
        public virtual TAB_SUBDEPARTMENT_MASTER TAB_SUBDEPARTMENT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_TOOL_TALK_CONFIG_DAILY_ITEMS> TAB_TOOL_TALK_CONFIG_DAILY_ITEMS { get; set; }
    }
}
