//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ROLE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_ROLE_MASTER()
        {
            this.TAB_MENU_ROLE_MAPPING = new HashSet<TAB_MENU_ROLE_MAPPING>();
            this.TAB_ROLE_MENU_MAPPING = new HashSet<TAB_ROLE_MENU_MAPPING>();
            this.TAB_ROLE_MENU_MAPPING1 = new HashSet<TAB_ROLE_MENU_MAPPING>();
            this.TAB_ROLE_MENU_MAPPING2 = new HashSet<TAB_ROLE_MENU_MAPPING>();
            this.TAB_USER_ROLE_MAPPING = new HashSet<TAB_USER_ROLE_MAPPING>();
            this.TAB_USER_ROLE_MAPPING1 = new HashSet<TAB_USER_ROLE_MAPPING>();
            this.TAB_USER_ROLE_MAPPING2 = new HashSet<TAB_USER_ROLE_MAPPING>();
        }
    
        public System.Guid ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public System.Guid COMPANY_ID { get; set; }
        public System.DateTime created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string status { get; set; }
        public string IS_EDITABLE { get; set; }
    
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER1 { get; set; }
        public virtual TAB_COMPANY_MASTER TAB_COMPANY_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MENU_ROLE_MAPPING> TAB_MENU_ROLE_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ROLE_MENU_MAPPING> TAB_ROLE_MENU_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ROLE_MENU_MAPPING> TAB_ROLE_MENU_MAPPING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_ROLE_MENU_MAPPING> TAB_ROLE_MENU_MAPPING2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING2 { get; set; }
    }
}
