//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_WORKFORCE_EXIT_APPROVER
    {
        public System.Guid EXIT_APPROVER_ID { get; set; }
        public System.Guid EXIT_ID { get; set; }
        public Nullable<System.Guid> APPROVE_BY { get; set; }
        public Nullable<System.DateTime> APPROVE_DATE { get; set; }
        public string APPROVER_STATUS { get; set; }
        public string REMARK { get; set; }
    }
}
