//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ACTIVITY_DETAILS
    {
        public Nullable<System.Guid> USER_ID { get; set; }
        public string USER_OPERATION { get; set; }
        public string PAGE_NAME { get; set; }
        public string REMARK { get; set; }
        public System.DateTime created_date { get; set; }
    }
}
