//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_BIOMETRIC_DATABASE
    {
        public int ID { get; set; }
        public string MDBFILENAME { get; set; }
        public Nullable<System.Guid> COMPANY_ID { get; set; }
        public string STATUS { get; set; }
        public string file_location { get; set; }
    }
}
