//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_MENU()
        {
            this.TAB_MENU_ROLE_MAPPING = new HashSet<TAB_MENU_ROLE_MAPPING>();
            this.TAB_SUBMENU = new HashSet<TAB_SUBMENU>();
        }
    
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ACTIVE { get; set; }
        public string ICONCLASS { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public Nullable<int> ORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_MENU_ROLE_MAPPING> TAB_MENU_ROLE_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_SUBMENU> TAB_SUBMENU { get; set; }
    }
}
