//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MAIL_TEMPLATE
    {
        public int TAMPLATE_ID { get; set; }
        public string TEMPLATE_FOR { get; set; }
        public string TEMPLATE_CONTANT { get; set; }
        public string CC_MAIL { get; set; }
    }
}
