//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.App.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApplicationEntities : DbContext
    {
        public ApplicationEntities()
            : base("name=ApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_AGENCY_MASTER> TAB_AGENCY_MASTER { get; set; }
        public virtual DbSet<TAB_BUILDING_MASTER> TAB_BUILDING_MASTER { get; set; }
        public virtual DbSet<TAB_DEPARTMENT_MASTER> TAB_DEPARTMENT_MASTER { get; set; }
        public virtual DbSet<TAB_FLOOR_MASTER> TAB_FLOOR_MASTER { get; set; }
        public virtual DbSet<TAB_LEVEL_MASTER> TAB_LEVEL_MASTER { get; set; }
        public virtual DbSet<TAB_SHIFT_MASTER> TAB_SHIFT_MASTER { get; set; }
        public virtual DbSet<TAB_SKILL_MASTER> TAB_SKILL_MASTER { get; set; }
        public virtual DbSet<TAB_WORKFLOW_MASTER> TAB_WORKFLOW_MASTER { get; set; }
        public virtual DbSet<TAB_ACTIVITY_DETAILS> TAB_ACTIVITY_DETAILS { get; set; }
        public virtual DbSet<TAB_MENU_ROLE_MAPPING> TAB_MENU_ROLE_MAPPING { get; set; }
        public virtual DbSet<TAB_ERROR_LOGS> TAB_ERROR_LOGS { get; set; }
        public virtual DbSet<TAB_BANK_MASTER> TAB_BANK_MASTER { get; set; }
        public virtual DbSet<TAB_EMP_STATUS_MASTER> TAB_EMP_STATUS_MASTER { get; set; }
        public virtual DbSet<TAB_EMPL_TYPE_MASTER> TAB_EMPL_TYPE_MASTER { get; set; }
        public virtual DbSet<TAB_MARITAL_STATUS_MASTER> TAB_MARITAL_STATUS_MASTER { get; set; }
        public virtual DbSet<TAB_MENU_MASTER> TAB_MENU_MASTER { get; set; }
        public virtual DbSet<TAB_STATE_CITY_MASTER> TAB_STATE_CITY_MASTER { get; set; }
        public virtual DbSet<TAB_STATE_MASTER> TAB_STATE_MASTER { get; set; }
        public virtual DbSet<TAB_WF_DESIGNATION_MASTER> TAB_WF_DESIGNATION_MASTER { get; set; }
        public virtual DbSet<TAB_WORFORCE_TYPE> TAB_WORFORCE_TYPE { get; set; }
        public virtual DbSet<TAB_WORKFORCE_EDU_MASTER> TAB_WORKFORCE_EDU_MASTER { get; set; }
        public virtual DbSet<TAB_ROLE_MENU_MAPPING> TAB_ROLE_MENU_MAPPING { get; set; }
        public virtual DbSet<TAB_REC_MASTER> TAB_REC_MASTER { get; set; }
        public virtual DbSet<TAB_WF_WORK_DETAILS> TAB_WF_WORK_DETAILS { get; set; }
        public virtual DbSet<TAB_ALL_MAIL> TAB_ALL_MAIL { get; set; }
        public virtual DbSet<TAB_ALL_SMS> TAB_ALL_SMS { get; set; }
        public virtual DbSet<TAB_ALL_WHATSAPP> TAB_ALL_WHATSAPP { get; set; }
        public virtual DbSet<Logs_Fatal> Logs_Fatal { get; set; }
        public virtual DbSet<Logs_Info> Logs_Info { get; set; }
        public virtual DbSet<Logs_Trace> Logs_Trace { get; set; }
        public virtual DbSet<Logs_Warn> Logs_Warn { get; set; }
        public virtual DbSet<TAB_WORKFORCE_MASTER> TAB_WORKFORCE_MASTER { get; set; }
        public virtual DbSet<TAB_HOLIDAY> TAB_HOLIDAY { get; set; }
        public virtual DbSet<TAB_WORKFORCE_LEAVES> TAB_WORKFORCE_LEAVES { get; set; }
        public virtual DbSet<TAB_WORKFORCE_DAILYWORK_MASTER> TAB_WORKFORCE_DAILYWORK_MASTER { get; set; }
        public virtual DbSet<TAB_WORKFORCE_SALARY> TAB_WORKFORCE_SALARY { get; set; }
        public virtual DbSet<TAB_FAULTY_PUNCHES> TAB_FAULTY_PUNCHES { get; set; }
        public virtual DbSet<TAB_BIOMETRIC_DATABASE> TAB_BIOMETRIC_DATABASE { get; set; }
        public virtual DbSet<TAB_BIOMETRIC> TAB_BIOMETRIC { get; set; }
        public virtual DbSet<TAB_BUILDING_DEPARTMENT_MAPPING> TAB_BUILDING_DEPARTMENT_MAPPING { get; set; }
        public virtual DbSet<TAB_CONSTANT_DATA> TAB_CONSTANT_DATA { get; set; }
        public virtual DbSet<TAB_MAIL_TEMPLATE> TAB_MAIL_TEMPLATE { get; set; }
        public virtual DbSet<TAB_MRF_APPROVER> TAB_MRF_APPROVER { get; set; }
        public virtual DbSet<TAB_SPECIAL_ALLOWANCE> TAB_SPECIAL_ALLOWANCE { get; set; }
        public virtual DbSet<TAB_USER_DEPARTMENT_MAPPING> TAB_USER_DEPARTMENT_MAPPING { get; set; }
        public virtual DbSet<TAB_WORKFORCE_EXIT> TAB_WORKFORCE_EXIT { get; set; }
        public virtual DbSet<TAB_WORKFORCE_EXIT_APPROVER> TAB_WORKFORCE_EXIT_APPROVER { get; set; }
        public virtual DbSet<TAB_WORKFORCE_PHOTO_MASTER> TAB_WORKFORCE_PHOTO_MASTER { get; set; }
        public virtual DbSet<TAB_USER_ROLE_MAPPING> TAB_USER_ROLE_MAPPING { get; set; }
        public virtual DbSet<TAB_WORKFLOW_MAPPING_MASTER> TAB_WORKFLOW_MAPPING_MASTER { get; set; }
        public virtual DbSet<TAB_COMPANY_MASTER> TAB_COMPANY_MASTER { get; set; }
        public virtual DbSet<TAB_LOGIN_MASTER> TAB_LOGIN_MASTER { get; set; }
        public virtual DbSet<TAB_MENU> TAB_MENU { get; set; }
        public virtual DbSet<TAB_MRF> TAB_MRF { get; set; }
        public virtual DbSet<TAB_MRF_DETAILS> TAB_MRF_DETAILS { get; set; }
        public virtual DbSet<TAB_ROLE_MASTER> TAB_ROLE_MASTER { get; set; }
        public virtual DbSet<TAB_SUBMENU> TAB_SUBMENU { get; set; }
        public virtual DbSet<TAB_SUBDEPARTMENT_MASTER> TAB_SUBDEPARTMENT_MASTER { get; set; }
        public virtual DbSet<TAB_ASSET_ALLOCATION> TAB_ASSET_ALLOCATION { get; set; }
        public virtual DbSet<TAB_ASSET_MASTER> TAB_ASSET_MASTER { get; set; }
        public virtual DbSet<TAB_TRAINNING_MASTER> TAB_TRAINNING_MASTER { get; set; }
        public virtual DbSet<TAB_TRAINNING_WORKFORCE> TAB_TRAINNING_WORKFORCE { get; set; }
        public virtual DbSet<TAB_GATEPASS> TAB_GATEPASS { get; set; }
        public virtual DbSet<TAB_TOOL_TALK_MASTER> TAB_TOOL_TALK_MASTER { get; set; }
        public virtual DbSet<TAB_TOOL_TALK_CONFIGURATION> TAB_TOOL_TALK_CONFIGURATION { get; set; }
        public virtual DbSet<TAB_TOOL_TALK_DAILY_CHECKLIST> TAB_TOOL_TALK_DAILY_CHECKLIST { get; set; }
        public virtual DbSet<TAB_TRAINNING_WORKFORCE_MAPPING> TAB_TRAINNING_WORKFORCE_MAPPING { get; set; }
        public virtual DbSet<TAB_ITEM_CODE> TAB_ITEM_CODE { get; set; }
        public virtual DbSet<TAB_TOOL_TALK_CONFIG_DAILY_ITEMS> TAB_TOOL_TALK_CONFIG_DAILY_ITEMS { get; set; }
        public virtual DbSet<TAB_EMPLOYEE_TRANSFER> TAB_EMPLOYEE_TRANSFER { get; set; }
        public virtual DbSet<TAB_ITEM_OPERATION_MASTER> TAB_ITEM_OPERATION_MASTER { get; set; }
        public virtual DbSet<TAB_WORKFORCE_DAILYWORK> TAB_WORKFORCE_DAILYWORK { get; set; }
        public virtual DbSet<TAB_WORKFORCE_SALARY_MASTER> TAB_WORKFORCE_SALARY_MASTER { get; set; }
    
        public virtual ObjectResult<AccountValidateUser_Result> ValidateUser(string uSERNAME, string pASSWORD)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccountValidateUser_Result>("ValidateUser", uSERNAMEParameter, pASSWORDParameter);
        }
    
        public virtual int InsertBioMetricTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertBioMetricTable");
        }
    
        public virtual ObjectResult<SelectActiveMRF_Result> SelectActiveMRF(Nullable<System.Guid> cOMPANYID)
        {
            var cOMPANYIDParameter = cOMPANYID.HasValue ?
                new ObjectParameter("COMPANYID", cOMPANYID) :
                new ObjectParameter("COMPANYID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectActiveMRF_Result>("SelectActiveMRF", cOMPANYIDParameter);
        }
    
        public virtual int GetUserMenu(Nullable<System.Guid> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetUserMenu", uSER_IDParameter);
        }
    
        public virtual ObjectResult<UserMenu_Result> USP_USER_MENU(Nullable<System.Guid> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserMenu_Result>("USP_USER_MENU", uSER_IDParameter);
        }
    }
}
