Update [WFMSUMITMRG].[dbo].[TAB_SUBMENU] set ACTION_NAME='Create' where id='56514AD4-6D66-EB11-BF71-A45D3669901F'

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER] DROP CONSTRAINT [FK_TAB_WORKFORCE_PHOTO_MASTER_TAB_WORKFORCE_MASTER]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER] DROP CONSTRAINT [DF__TAB_WORKF__CREAT__314D4EA8]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER] DROP CONSTRAINT [DF__TAB_WORKF__PHOTO__30592A6F]
GO

/****** Object:  Table [dbo].[TAB_WORKFORCE_PHOTO_MASTER]    Script Date: 10/08/2021 12:12:19 ******/
DROP TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER]
GO

/****** Object:  Table [dbo].[TAB_WORKFORCE_PHOTO_MASTER]    Script Date: 10/08/2021 12:12:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER](
	[PHOTO_ID] [uniqueidentifier] NOT NULL,
	[WF_ID] [uniqueidentifier] NOT NULL,
	[PHOTO] [image] NULL,
	[EMP_SIGNATURE] [image] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[UPDATED_BY] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[PHOTO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER] ADD  DEFAULT (newsequentialid()) FOR [PHOTO_ID]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER]  WITH CHECK ADD  CONSTRAINT [FK_TAB_WORKFORCE_PHOTO_MASTER_TAB_WORKFORCE_MASTER] FOREIGN KEY([WF_ID])
REFERENCES [dbo].[TAB_WORKFORCE_MASTER] ([WF_ID])
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_PHOTO_MASTER] CHECK CONSTRAINT [FK_TAB_WORKFORCE_PHOTO_MASTER_TAB_WORKFORCE_MASTER]
GO


