/****** Object:  Table [dbo].[TAB_BIOMETRIC_DATABASE]    Script Date: 8/12/2021 11:36:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TAB_BIOMETRIC_DATABASE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MDBFILENAME] [varchar](50) NULL,
	[COMPANY_ID] [uniqueidentifier] NULL,
	[STATUS] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


