INSERT [dbo].[TAB_ITEM_MASTER] ([COMPANY_ID], [ITEM_ID], [DEPT_ID], [ITEM_CODE], [ITEM_NAME], [CREATED_DATE], [CREATED_BY], [UPDATED_DATE], [UPDATED_BY], [STATUS]) VALUES (N'a8e171fa-ac3f-eb11-9092-a0a8cdb0f79c', N'50cb5af6-e65b-eb11-9474-8cdcd4d2c4bc', N'3a3cc7d1-e65b-eb11-9474-8cdcd4d2c4bc', N' DUTY', N'DUTY', CAST(N'2021-01-21T18:18:36.907' AS DateTime), NULL, NULL, NULL, N'Y')
INSERT [dbo].[TAB_ITEM_OPERATION_MASTER] ([UNIQUE_OPERATION_ID], [COMPANY_ID], [ITEM_ID], [RATE], [OPERATION], [PERCENTAGE], [RATE_APPLIED_DATE], [CREATED_DATE], [CREATED_BY], [UPDATED_DATE], [UPDATED_BY], [STATUS]) VALUES (N'35846c11-e75b-eb11-9474-8cdcd4d2c4bc', N'a8e171fa-ac3f-eb11-9092-a0a8cdb0f79c', N'50cb5af6-e65b-eb11-9474-8cdcd4d2c4bc', 0, N'DUTY', 0, CAST(N'2021-01-21' AS Date), CAST(N'2021-01-21T18:19:21.950' AS DateTime), NULL, NULL, NULL, N'N')

INSERT [dbo].[TAB_ITEM_MASTER] ([COMPANY_ID], [ITEM_ID], [DEPT_ID], [ITEM_CODE], [ITEM_NAME], [CREATED_DATE], [CREATED_BY], [UPDATED_DATE], [UPDATED_BY], [STATUS]) VALUES (N'a8e171fa-ac3f-eb11-9092-a0a8cdb0f79c', N'51cb5af6-e65b-eb11-9474-8cdcd4d2c4bc', N'3a3cc7d1-e65b-eb11-9474-8cdcd4d2c4bc', N'OVERTIME', N'Over Time', CAST(N'2021-01-21T18:18:36.907' AS DateTime), NULL, NULL, NULL, N'N')
INSERT [dbo].[TAB_ITEM_OPERATION_MASTER] ([UNIQUE_OPERATION_ID], [COMPANY_ID], [ITEM_ID], [RATE], [OPERATION], [PERCENTAGE], [RATE_APPLIED_DATE], [CREATED_DATE], [CREATED_BY], [UPDATED_DATE], [UPDATED_BY], [STATUS]) VALUES (N'36846c11-e75b-eb11-9474-8cdcd4d2c4bc', N'a8e171fa-ac3f-eb11-9092-a0a8cdb0f79c', N'51cb5af6-e65b-eb11-9474-8cdcd4d2c4bc', 0, N'Over Time', 0, CAST(N'2021-01-21' AS Date), CAST(N'2021-01-21T18:19:21.950' AS DateTime), NULL, NULL, NULL, N'N')

DROP TABLE [dbo].[TAB_WORKFORCE_DAILYWORK]
CREATE TABLE [dbo].[TAB_WORKFORCE_DAILYWORK](
	[ID] [uniqueidentifier] NOT NULL,
	[WF_ID] [uniqueidentifier] NOT NULL,
	[RATE] [float] NOT NULL,
	[WORK_DATE] [date] NULL,
	[UNIQUE_OPERATION_ID] [uniqueidentifier] NOT NULL,
	[ITEM_ID] [uniqueidentifier] NOT NULL,
	[QTY] [int] NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[UPDATED_BY] [varchar](100) NULL,
 CONSTRAINT [PK__TAB_WORK__3214EC278A2F576D] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK] ADD  CONSTRAINT [DF__TAB_WORKFORC__ID__59B045BD]  DEFAULT (newsequentialid()) FOR [ID]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK] ADD  CONSTRAINT [DF__TAB_WORKF__CREAT__5AA469F6]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK]  WITH CHECK ADD  CONSTRAINT [FK__TAB_WORKF__WF_ID__5B988E2F] FOREIGN KEY([WF_ID])
REFERENCES [dbo].[TAB_WORKFORCE_MASTER] ([WF_ID])
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK] CHECK CONSTRAINT [FK__TAB_WORKF__WF_ID__5B988E2F]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK]  WITH CHECK ADD  CONSTRAINT [FK_TAB_WORKFORCE_DAILYWORK_TAB_ITEM_MASTER] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[TAB_ITEM_MASTER] ([ITEM_ID])
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK] CHECK CONSTRAINT [FK_TAB_WORKFORCE_DAILYWORK_TAB_ITEM_MASTER]
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK]  WITH CHECK ADD  CONSTRAINT [FK_TAB_WORKFORCE_DAILYWORK_TAB_ITEM_OPERATION_MASTER] FOREIGN KEY([UNIQUE_OPERATION_ID])
REFERENCES [dbo].[TAB_ITEM_OPERATION_MASTER] ([UNIQUE_OPERATION_ID])
GO

ALTER TABLE [dbo].[TAB_WORKFORCE_DAILYWORK] CHECK CONSTRAINT [FK_TAB_WORKFORCE_DAILYWORK_TAB_ITEM_OPERATION_MASTER]
GO


